### ISSUE TITLE
Välipalautus 2 vertaisarviointi

### ISSUE THREAD

**Issue by AlluSu** [acidmole/teammate#1]
Hyvää:
Työ on kaikinpuolin hyvässä vaiheessa ja näyttää siltä että on selkeä visio mitä tehdään ja miten. Käyttöliittymä on selkeä ja intuitiivinen käyttää. Ulkoasuunkin jo panostettu alkuvaiheessa. Kokeilin sovellusta nopeasti myös Lynx tekstiselaimella ja toimi hyvin.

Parannettavaa:
Tietokannassa on melko kryptisen nimisiä sarakkeita jos kohdealue (koripallo) ei ole tuttu, kuten esimerkiksi "fg", "fga", "three_a" jne. Näitä voisi jotenkin "kansantajuistaa" jos esimerkiksi kävisi niin että sovelluksen ylläpito ja kehitys siirtyisi jollekkin joka ei tunne kohdealuetta yhtä hyvin.

Kun sovellukseen luodaan uusi käyttäjä, voisi kentät johon tiedot syötetään olla allekkain. Monessa sovelluksessa jossa syötetään käyttäjätiedot ja luodaan uusi käyttäjä on  yleensä allekkain kaikki tietojen tallettamiseen käytettävät kentät. Käyttäjällekkin jää näin parempi käyttäjäkokemus, koska käyttöliittymästä löytyisi jotain "tuttua".

**Comment by acidmole** [comment]
Palautteen mukaisiin toimenpiteisiin ryhdytty!
